version: "3"
services:
#  api:
#    image: turnip-market:latest
#    container_name: turnip-market-api
#    ports:
#      - "4000:4000"
#    environment:
#      NODE_ENV: "production"
#    command: /bin/bash -c "cd packages/api; node dist/main.js"
  ui:
    image: turnip-market:latest
    container_name: turnip-market-ui
    environment:
      NODE_ENV: "production"
    volumes:
      - ui-volume:/var/app/packages/ui/build
  nginx:
    image: nginx:latest
    ports:
      - "5000:80"
    links:
      - ui
    volumes:
      - ui-volume:/usr/share/nginx/html
volumes:
  ui-volume:
